[package]
name = "f-analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.machine-prime]

version = "1.5.5"
features = ["ssmr","wide","internal"]
